---
dist: trusty
language: ruby
cache: bundler
sudo: false
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system $RUBYGEMS_VERSION
  - gem update bundler
  - gem --version
  - bundle -v
script:
  bundle exec rake rubocop
matrix:
  include:
    - rvm: 2.4.10
    - rvm: 2.6.6
    - rvm: 2.7.2
